### ISSUE TITLE
[Feature] ServoDriver class: servo.setAngle(i, angle, rotationspeed)

### ISSUE THREAD

**Issue by dsyleixa** [Seeed-Studio/Seeed_PCA9685#3]
feature request: ServoDriver class: servo.setAngle(byte i, int angle, float rotationspeed)
i: servo channel
angle: degrees (endpoint)
rotationspeed: degrees per second

e.g.,
```
servo.setAngle(i, 90); // let the servo move to position 90° immediately
delay(1000);
servo.setAngle(i, 180, 10.0); // moves the servo from the current position (90°) to position 180° by a rotation speed of 10°/sec
```

The function must not be blocking, so that a following command can be started immediately before the further movement has been finished (simultaneous movement)

servo.setAngle(1, 180, 10.0);
servo.setAngle(2, 45, 5.0);

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

We will consider your request.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
